export const SEO_DATA = {
  title: "FF : Friend Forever",
  description: "Save your memories forever with Friend Forever",
  locate: "Thailand",
  tabimage: "/images/FriendLight.png",
  url: "FF : Friend Forever",
  image: "/images/FriendLight.png",
  width: "500",
  height: "500",
  site_name: "Friend Forever™",
  locale: "th_TH",
  locale_alternate: "en_US",
  keywords: "Save your memories forever with Friend Forever",
  author: "Friend Forever™",
  copyright: "Copyright © 2022 by Friend Forever™",
  robots: "index,follow",
  googlebot: "",
  google: "",
  google_site_verification: "",
}